---

- name: AWS S3 버킷 생성 및 설정 (조건에 의한 S3 버킷 생성 및 설정)
  amazon.aws.s3_bucket:
    state: present #생성
    name: "{{ s3_bucket_name }}" # 생성할 버킷 이름
    region: "{{ region }}" #리전 위치
    object_ownership: "BucketOwnerEnforced" # 객체 소유권 설정
    versioning: no # 버전 관리 설정
    encryption: "AES256" # 암호화 설정
    public_access: # 퍼블릭 액세스 설정
      block_public_acls: true
      ignore_public_acls: true
      block_public_policy: true
      restrict_public_buckets: true
    tags:
      Name: project3_bucket # S3 테그 이름
  when: S3_BUCKET_STATE == "present"  # 실행 플레이북 조건이 "present"일 때만 실행
  
- name: AWS S3 버킷 삭제
  amazon.aws.s3_bucket:
    name: "{{ s3_bucket_name }}"
    region: "{{ region }}"
    state: absent
  when: S3_BUCKET_STATE == "absent"