---
- name: Create IAM policy and role when EC2 is present
  block:
    - name: Create full S3 access IAM managed policy
      iam_managed_policy:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        policy_name: "{{ iam_policy_name }}"
        policy_description: "Full access to S3 for automation"
        policy: "{{ lookup('file', 'full_s3_policy.json.j2') }}"
        state: present
        region: "{{ region }}"

    - name: Create IAM Role and attach managed policy
      iam_role:
        name: "{{ iam_role_name }}"
        assume_role_policy_document: "{{ lookup('file', 'assume_role_policy.json') }}"
        managed_policy:
          - "arn:aws:iam::{{ aws_account_id }}:policy/{{ iam_policy_name }}"
        state: present
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
  when: ec2_state == "present"


- name: Delete IAM policy and role when EC2 is absent
  block:
    - name: Delete IAM managed policy
      iam_managed_policy:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        policy_name: "{{ iam_policy_name }}"
        state: absent
        region: "{{ region }}"

    - name: Delete CodeDeploy EC2 Role
      iam_role:
        name: project3-code-deploy-ec2-role
        state: absent
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
  when: ec2_state == "absent"

