---
- name: Create ED25519 key pair and save private key into a file(ED25519방식을 이용한 키생성)
  amazon.aws.ec2_key:
    region: "{{ region }}" 
    name: project3-key
    key_type: ed25519
    file_name: /root/aws_ssh_rsa
  when: key_state == "present"

- name: remove key pair from AWS by name(키페어 이름을 통한 키삭제)
  amazon.aws.ec2_key:
    region: "{{ region }}" 
    name: project3-key
    state: absent   
  when: key_state == "absent"
