---
# ------------------- 생성 작업 -------------------

- block:
    - name: Get VPC info (VPC 정보 조회)
      amazon.aws.ec2_vpc_net_info:
        filters:
          "tag:Name": project3-vpc
        region: "{{ region }}"
      register: vpc_info

    - name: Get public subnet info (project3-public-2a) (Public Subnet 정보 조회)
      amazon.aws.ec2_vpc_subnet_info:
        filters:
          "tag:Name": project3-public-2a
          vpc-id: "{{ vpc_info.vpcs[0].vpc_id }}"
        region: "{{ region }}"
      register: public_subnet_info

    - name: Create Elastic IP for NAT Gateway (NAT Gateway용 Elastic IP 생성)
      amazon.aws.ec2_eip:
        region: "{{ region }}"
        in_vpc: true
        state: present
      register: nat_eip

    - name: Create Internet Gateway and attach to VPC (Internet Gateway 생성 및 VPC 연결)
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
        region: "{{ region }}"
        tags:
          Name: project3-igw
        state: present

    - name: Create NAT Gateway in public subnet (ap-northeast-2a) (Public Subnet에 NAT Gateway 생성)
      amazon.aws.ec2_vpc_nat_gateway:
        subnet_id: "{{ public_subnet_info.subnets[0].id }}"
        allocation_id: "{{ nat_eip.allocation_id }}"
        region: "{{ region }}"
        state: present
        tags:
          Name: project3-nat

  when: vpc_igw_nat_state == "present"


- block:
    - name: Get VPC info (VPC 정보 조회
      amazon.aws.ec2_vpc_net_info:
        filters:
          "tag:Name": project3-vpc
        region: "{{ region }}"
      register: vpc_info

    - name: Get public subnet info (project3-public-2a) (Public Subnet 정보 조회)
      amazon.aws.ec2_vpc_subnet_info:
        filters:
          "tag:Name": project3-public-2a
          vpc-id: "{{ vpc_info.vpcs[0].vpc_id }}"
        region: "{{ region }}"
      register: public_subnet_info

    - name: Get NAT Gateway info (NAT Gateway 정보 조회)
      amazon.aws.ec2_vpc_nat_gateway_info:
        filters:
          subnet-id: "{{ public_subnet_info.subnets[0].id }}"
        region: "{{ region }}"
      register: natgw_info

    - name: Release Elastic IPs before deleting NAT Gateway (NAT Gateway 삭제 전 EIP 해제)
      amazon.aws.ec2_eip:
        allocation_id: "{{ item.nat_gateway_addresses[0].allocation_id }}"
        region: "{{ region }}"
        state: absent
      loop: "{{ natgw_info.nat_gateways }}"


    - name: Delete NAT Gateway (NAT Gateway 삭제)
      amazon.aws.ec2_vpc_nat_gateway:
        nat_gateway_id: "{{ item.nat_gateway_id }}"
        region: "{{ region }}"
        state: absent
      loop: "{{ natgw_info.nat_gateways }}"


    - name: Wait for NAT Gateway deletion (NAT Gateway 삭제 완료 대기)
      amazon.aws.ec2_vpc_nat_gateway_info:
        filters:
          subnet-id: "{{ public_subnet_info.subnets[0].id }}"
        region: "{{ region }}"
      register: natgw_wait
      until: natgw_wait.nat_gateways | length == 0
      retries: 40
      delay: 15

    - name: Get Internet Gateway info (Internet Gateway 정보 조회)
      amazon.aws.ec2_vpc_igw_info:
        filters:
          attachment.vpc-id: "{{ vpc_info.vpcs[0].vpc_id }}"
        region: "{{ region }}"
      register: igw_info

    - name: Detach IGW from VPC (Internet Gateway VPC 연결 해제)
      amazon.aws.ec2_vpc_igw:
        internet_gateway_id: "{{ item.internet_gateway_id }}"
        region: "{{ region }}"
        state: absent
      loop: "{{ igw_info.internet_gateways }}"


  when: vpc_igw_nat_state == "absent"

