---
- name: Create CodeDeploy Role(CodeDeploy Role 생성)
  iam_role:
    name: "{{ iam_role_name }}"
    assume_role_policy_document: "{{ lookup('file', 'assume_codedeploy.json') }}"
    managed_policy:
      - "arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole"
    state: present
    region: "{{ region }}"
  when: iam_role_state == "present"

- name: Delete CodeDeploy Role(조건에 의한 Role 삭제)
  iam_role:
    name: "{{ iam_role_name }}"
    state: absent
    region: "{{ region }}"
  when: iam_role_state == "absent"
