---

- block:
    - name: Get VPC info(VPC 정보 Import)
      amazon.aws.ec2_vpc_net_info:
        region: "{{ region }}"
        filters:
          "tag:Name": "{{ vpc_name }}"
      register: vpc_info

    - name: Get public subnet IDs (VPC_info를 이용하여 Public Subnet ID 가져오기)
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ region }}"
        filters:
          "tag:Name": "{{ item }}"
          vpc-id: "{{ vpc_info.vpcs[0].vpc_id }}"
      with_items:
        - project3-public-2a
        - project3-public-2c
      register: subnet_results

    - name: Set subnet_ids fact (서브넷 ID를 fact로 변환)
      set_fact:
        subnet_ids: >-
          {{ subnet_results.results | map(attribute='subnets') | map('first') | map(attribute='id') | list }}
      when: alb_state == "present"

    - name: Create Application Load Balancer (ALB) with HTTP 80 listener only(ALB 80포트 리스너 추가)
      community.aws.elb_application_lb:
        name: project3-alb
        subnets: "{{ subnet_ids }}"
        security_groups: "{{ sg_alb_name }}"
        scheme: internet-facing
        listeners:
          - Protocol: HTTP
            Port: 80
            DefaultActions:
              - Type: forward
                TargetGroupName: project3-jenkins-tg 
        state: present
        region: "{{ region }}"
      register: alb_info
  when: alb_state == "present"

- block:
    - name: Delete Application Load Balancer (조건에 의한 ALB 삭제)
      community.aws.elb_application_lb:
        name: project3-alb
        state: absent
        region: "{{ region }}"
      register: delete_alb_result
  when: alb_state == "absent"
