---

- name: Check VPC info after creation or before deletion(보안 그룹 생성 또는 삭제 전 사용)
  amazon.aws.ec2_vpc_net_info:
    region: "{{ region }}"
    filters:
      "tag:Name": project3-vpc
  register: vpc_info
  when: security_group_state in ["present", "absent"]

- block:
    - name: Create security groups(조건을 이용한 보안 그룹 생성)
      amazon.aws.ec2_group:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
        region: "{{ region }}"
        rules: |
          [{% for port in item.ports %}
            {"proto": "tcp", "from_port": {{ port }}, "to_port": {{ port }}, "cidr_ip": "0.0.0.0/0"}{% if not loop.last %},{% endif %}
          {% endfor %}]
        rules_egress:
          - proto: -1
            from_port: 0
            to_port: 0
            cidr_ip: 0.0.0.0/0
        tags:
          Name: "{{ item.name }}"
      register: sg_results
      loop: "{{ security_groups }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Set SG IDs as global variables (생성된 보안 그룹의 ID를 변수로 저장)
      set_fact:
        "{{ item.item.var_name }}": "{{ item.group_id }}"
      loop: "{{ sg_results.results }}"

  when: security_group_state == "present"


- block:
    - name: Delete security groups(보안 그룹 삭제)
      amazon.aws.ec2_group:
        name: "{{ item.name }}"
        vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
        region: "{{ region }}"
        state: absent
      loop: "{{ security_groups }}"
      loop_control:
        label: "{{ item.name }}"

  when: security_group_state == "absent"
