---

- block:

    - name: Get VPC info(VPC 정보 추출)
      amazon.aws.ec2_vpc_net_info:
        region: "{{ region }}"
        filters:
          "tag:Name": project3-vpc
      register: vpc_info

    - name: Check VPC info after creation or before deletion(Private Subnet 정보 추출)
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ region }}"
        filters:
          "tag:Name": project3-private-2a
          vpc-id: "{{ vpc_info.vpcs[0].vpc_id }}"
      register: subnet_info

    - name: Launch Target EC2 instance (Target EC2 인스턴스 생성)
      amazon.aws.ec2_instance:
        name: "{{ instance_name }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        user_data: "{{ lookup('file', 'files/userdata.sh') }}"
        region: "{{ region }}"
        vpc_subnet_id: "{{ subnet_info.subnets[0].subnet_id }}"
        security_groups: "{{ security_groups }}"
        network:
          assign_public_ip: false
        wait: true
        count: 1
        tags:
          Name: project3-target-ec2
      register: ec2_info

  when: EC2_state == "present"

- block:

    - name: Get Jenkins EC2 instance info(종료 대상 EC2 인스턴스 정보 추출)
      amazon.aws.ec2_instance_info:
        region: "{{ region }}"
        filters:
          tag:Name: "{{ instance_name }}"
          instance-state-name: running
      register: Target_ec2_info

    - name: Terminate Jenkins EC2 instance(EC2 인스턴스 종료)
      amazon.aws.ec2_instance:
        instance_ids: "{{ Target_ec2_info.instances | map(attribute='instance_id') | list }}"
        region: "{{ region }}"
        state: absent
        wait: true

  when: EC2_state == "absent"
