- name: Delete CodeDeploy Application
  hosts: localhost
  gather_facts: false

  collections:
    - community.aws

  vars_files:
    - ../Code_deploy_Group/vars/vars.yml

  vars:
    state: delete

  roles:
    - Code_deploy_Group
