---

- block:  # 생성 관련 작업 블럭 (vpc_state가 'present'일 때 실행)
    - name: Create VPC (VPC 생성)
      amazon.aws.ec2_vpc_net:
        name: project3-vpc
        cidr_block: 10.3.0.0/16
        region: "{{ region }}"
        tenancy: default
        tags:
          Name: project3-vpc
      register: vpc_result

    - name: Check VPC info after creation (생성 후 VPC 정보 조회)
      amazon.aws.ec2_vpc_net_info:
        region: "{{ region }}"
        filters:
          "tag:Name": project3-vpc
      register: vpc_info

    - name: Set fact with VPC ID (after creation) (생성 후 VPC ID 설정)
      set_fact:
        vpc_id: "{{ vpc_result.vpc.id }}"
  when: vpc_state == "present"


- block:  # 삭제 관련 작업 블럭 (vpc_state가 'absent'일 때 실행)
    - name: Check VPC info before deletion (삭제 전 VPC 정보 조회)
      amazon.aws.ec2_vpc_net_info:
        region: "{{ region }}"
        filters:
          "tag:Name": project3-vpc
      register: vpc_info

    - name: Delete VPC (VPC 삭제)
      amazon.aws.ec2_vpc_net:
        region: "{{ region }}"
        vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
        state: absent

  when: vpc_state == "absent"
