---
- name: AWS 리소스 정보 조회 (region 변수 기준, VPC/서브넷/IGW/NAT Gateway 정보 조회)
  block:
    - name: Get VPC info (project3-vpc) (VPC 정보 조회)
      amazon.aws.ec2_vpc_net_info:
        region: "{{ region }}"
        filters:
          "tag:Name": project3-vpc
      register: vpc_info

    - name: Set VPC ID fact (VPC ID 변수 설정)
      set_fact:
        vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"

    - name: Get subnet info (서브넷 정보 조회)
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ region }}"
        filters:
          vpc-id: "{{ vpc_id }}"
      register: subnet_info

    - name: Get IGW info (IGW 정보 조회)
      amazon.aws.ec2_vpc_igw_info:
        region: "{{ region }}"
        filters:
          attachment.vpc-id: "{{ vpc_id }}"
      register: igw_info

    - name: Get NAT Gateway info (NAT Gateway 정보 조회)
      amazon.aws.ec2_vpc_nat_gateway_info:
        region: "{{ region }}"
        filters:
          vpc-id: "{{ vpc_id }}"
      register: natgw_info

- name: VPC Route Table 생성 (라우트 테이블 생성 및 구성)
  when: VPC_RT == "present"
  block:
    - name: Create and configure public route table (project3-public-rt) (퍼블릭 라우트 테이블 생성 및 서브넷 연결)
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        tags:
          Name: project3-public-rt
        subnets:
          - "{{ (subnet_info.subnets | selectattr('tags.Name', 'equalto', 'project3-public-2c') | list)[0].subnet_id }}"
          - "{{ (subnet_info.subnets | selectattr('tags.Name', 'equalto', 'project3-public-2a') | list)[0].subnet_id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw_info.internet_gateways[0].internet_gateway_id }}"
        state: present
        purge_routes: true
        purge_subnets: true
        purge_tags: true
    
    - name: Create and configure private route table 1 (project3-private-rtb-1) (프라이빗 라우트 테이블 1 생성 및 NAT Gateway 연결)
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        tags:
          Name: project3-private-rtb-1
        subnets:
          - "{{ (subnet_info.subnets | selectattr('tags.Name', 'equalto', 'project3-private-2a') | list)[0].subnet_id }}"
        routes:
          - dest: 0.0.0.0/0
            nat_gateway_id: "{{ natgw_info.result[0].nat_gateway_id }}"
        state: present
        purge_routes: true
        purge_subnets: true
        purge_tags: true
    
    - name: Create and configure private route table 2 (project3-private-rtb-2) (프라이빗 라우트 테이블 2 생성 및 NAT Gateway 연결)
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        tags:
          Name: project3-private-rtb-2
        subnets:
          - "{{ (subnet_info.subnets | selectattr('tags.Name', 'equalto', 'project3-private-2c') | list)[0].subnet_id }}"
        routes:
          - dest: 0.0.0.0/0
            nat_gateway_id: "{{ natgw_info.result[0].nat_gateway_id }}"
        state: present
        purge_routes: true
        purge_subnets: true
        purge_tags: true

- name: VPC Route Table 삭제 (라우트 테이블 및 연결된 리소스 삭제)
  when: VPC_RT == "absent"
  block:
    - name: 삭제할 라우트 테이블 정보 가져오기 (태그 이름으로) (삭제 대상 라우트 테이블 조회)
      amazon.aws.ec2_vpc_route_table_info:
        region: "{{ region }}"
        filters:
          vpc-id: "{{ vpc_id }}"
          "tag:Name":
            - project3-public-rt
            - project3-private-rtb-1
            - project3-private-rtb-2
      register: rtbs_to_delete_info

    - name: 각 라우트 테이블의 서브넷 연결 해제 (서브넷과의 라우트 테이블 연결 해제)
      amazon.aws.ec2_vpc_route_table:
        state: absent
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        route_table_id: "{{ item.route_table_id }}"
        subnets: "{{ item.associations | selectattr('association_state.state', 'equalto', 'associated') | map(attribute='subnet_id') | list }}"
      loop: "{{ rtbs_to_delete_info.route_tables }}"
      loop_control:
        label: "서브넷 연결 해제: {{ item.tags.Name | default('알 수 없는 라우트 테이블') }}"
      when: item.associations is defined and (item.associations | selectattr('association_state.state', 'equalto', 'associated') | list | length > 0)
      ignore_errors: yes

    - name: 각 라우트 테이블의 모든 라우트 삭제 (라우트 테이블 내 라우트 삭제)
      amazon.aws.ec2_vpc_route_table:
        state: absent
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        route_table_id: "{{ item.route_table_id }}"
        routes: >
          {{ item.routes | selectattr('gateway_id', '!=', 'local') |
             map('community.general.dict_helper.merge', {'state': 'absent'}) | list }}
      loop: "{{ rtbs_to_delete_info.route_tables }}"
      loop_control:
        label: "라우트 삭제: {{ item.tags.Name | default('알 수 없는 라우트 테이블') }}"
      when: item.routes is defined and item.routes | length > 0
      ignore_errors: yes

    - name: 라우트 테이블 삭제 (이름으로 개별 처리) (라우트 테이블 리소스 삭제)
      amazon.aws.ec2_vpc_route_table:
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        lookup: id
        route_table_id: "{{ (rtbs_to_delete_info.route_tables | selectattr('tags.Name', 'equalto', item) | list)[0].route_table_id }}"
        state: absent
      loop:
        - project3-public-rt
        - project3-private-rtb-1
        - project3-private-rtb-2
      loop_control:
        label: "라우트 테이블 삭제: {{ item }}"
